	<nav id="navbar">
		<form id="graphoptions" class="container navlist">
			<input type="hidden" name="setupfile" value="StateDEM"/>
			<select name="state" id="state" class="navitem">
				<option value="AK">Alaska</option>
				<option value="CA" selected="selected">California</option>
				<option value="CO">Colorado</option>
				<option value="ND">North Dakota</option>
				<option value="OH">Ohio</option>
				<option value="PA">Pennsylvania</option>
			</select>
			<select name="chamber" id="chamber" class="navitem">
				<option value="state:upper">Senate</option>
				<option value="state:lower">Assembly/House</option>
			</select>
			<select name="cycle" id="cycle" class="navitem">
				<option>2012</option>
				<option selected="selected">2010</option>
				<option>2008</option>
			</select>
		</form>
	</nav>
